[project]
name = "update-ip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lym", email = "liyumeng.1122@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "rich>=15.0.0",
]

[project.scripts]
update-ip = "update_ip:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "respx>=0.23.1",
]
